export const strings = {
  logo: {
    name: 'Haxball Kits',
    ariaLabel: 'Haxball Kits',
  },
  tabs: {
    ariaLabel: 'Secciones de Haxball Kits',
    myShirts: 'Mis camisetas',
    create: 'Crear',
    community: 'Comunidad',
    favorites: 'Favoritos',
  },
  pagination: {
    label: 'Paginación',
    previous: '‹ Anterior',
    next: 'Siguiente ›',
  },
  card: {
    removeFavorite: 'Quitar de favoritos',
    addFavorite: 'Agregar a favoritos',
    removeCommunity: 'Retirar de la comunidad',
    publishCommunity: 'Publicar en la comunidad',
    delete: 'Borrar camiseta',
  },
  viewState: {
    loading: 'Cargando camisetas…',
    empty: 'No hay camisetas para mostrar.',
    error: 'No se pudo cargar esta sección.',
  },
  comingSoon: 'Esta sección estará disponible próximamente.',
  lists: {
    emptyOwn: 'Todavía no tenés camisetas.',
    emptyCommunity: 'No hay camisetas en la comunidad.',
    emptyFavorites: 'Todavía no tenés favoritos.',
    createFirst: 'Crear tu primera camiseta',
    retry: 'Reintentar',
    loading: 'Cargando camisetas…',
    error: 'No se pudo cargar esta sección.',
    adminNote: 'El comando /colors solo funciona si sos admin de la sala.',
  },
  feedback: {
    appliedRed: 'Camiseta aplicada a Red',
    appliedBlue: 'Camiseta aplicada a Blue',
    noTab: 'No se encontró una pestaña de Haxball.',
    chatNotFound: 'No se encontró el chat de Haxball.',
    unexpectedGame: 'Ocurrió un error inesperado al aplicar la camiseta.',
    published: 'Camiseta publicada en la comunidad.',
    unpublished: 'Camiseta retirada de la comunidad.',
    publishConfirm: '¿Querés publicar esta camiseta en la comunidad?',
    unpublishConfirm: '¿Querés retirar esta camiseta de la comunidad?',
    deleteConfirm: '¿Querés borrar esta camiseta?',
    publishSaveWarning: 'Camiseta guardada, pero no se pudo publicar.',
    saved: 'Camiseta guardada.',
    deleted: 'Camiseta borrada.',
    favoriteAdded: 'Agregada a favoritos.',
    favoriteRemoved: 'Quitada de favoritos.',
    actionError: 'No se pudo completar la acción.',
  },
  confirm: {
    confirm: 'Confirmar',
    cancel: 'Cancelar',
  },
  colorPicker: {
    title: 'Elegir color',
    hex: 'Color hexadecimal',
    apply: 'Aplicar color',
  },
  errors: {
    INVALID_INPUT: 'Los datos ingresados no son válidos.',
    INVALID_STATE: 'El estado de la camiseta no permite completar esta acción.',
    NETWORK: 'No se pudo conectar con la comunidad.',
    NOT_FOUND: 'No se encontró la camiseta solicitada.',
    STORAGE: 'No se pudo acceder al almacenamiento local.',
    GAME: 'No se pudo aplicar la camiseta en Haxball.',
    UNKNOWN: 'Ocurrió un error inesperado.',
  },
  create: {
    name: 'Nombre',
    angle: 'Ángulo',
    angleValue: 'Valor del ángulo',
    textColor: 'Color del texto',
    textColorHex: 'Color del texto en hexadecimal',
    shirtColors: 'Colores de la camiseta',
    color: 'Color',
    removeColor: 'Eliminar color',
    addColor: 'Agregar color',
    publish: 'Publicar en la comunidad',
    save: 'Guardar camiseta',
    saving: 'Guardando…',
    errors: {
      name: 'Usá entre 1 y 24 caracteres, sin espacios al inicio o final.',
      angle: 'El ángulo debe ser un entero entre 0 y 359.',
      textColor: 'Usá un color hexadecimal válido en formato #RRGGBB.',
      colors: 'Agregá entre 1 y 3 colores hexadecimales válidos.',
    },
  },
} as const
